"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['OSC Countdown.py']
DATA_FILES = ['localSettings.json', 'Oceanix.json', 'TrojanBlue.json']
OPTIONS = {
    'iconfile':'timerIcns.icns'
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
